name: CI - Build e Teste do CinemaSystem

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o c√≥digo
        uses: actions/checkout@v3

      - name: 1.5. Configurar o Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: 2. Rodar o Build
        run: mvn clean package

      - name: 3. Rodar os Testes
        run: mvn test