name: CI - Build e Teste do CinemaSystem

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: cinemasystem
          POSTGRES_HOST_AUTH_METHOD: trust # Desabilita a autenticação por senha
        ports:
          - 5432:5432

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cinemasystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

    steps:
      - name: 1. Baixar o código
        uses: actions/checkout@v3

      - name: 1.5. Configurar o Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: 2. Esperar o Banco de Dados iniciar
        run: echo "Esperando 30s pelo Postgres..." && sleep 30

      - name: 3. Rodar Build e Testes
        run: mvn clean verify -e
